#!/usr/bin/env python3
"""Resolve, validate, and apply Doozo's local configuration.

This helper deliberately does not discover models or launch agents.  A host
workflow may pass its advertised capabilities with --capabilities-json; actual
route smoke tests belong to that host workflow.
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from dataclasses import dataclass
from typing import Any, Iterable, Optional, Tuple


SCRIPT_DIR = Path(__file__).resolve().parent
PLUGIN_DIR = SCRIPT_DIR.parent
DEFAULTS_PATH = PLUGIN_DIR / "defaults.json"

CONFIG_KEYS = {
    "schema_version",
    "preset",
    "max_workers",
    "model_fallback",
    "browser",
    "roles",
}
ROLE_NAMES = (
    "orchestrator",
    "scout",
    "implementer",
    "complex-implementer",
    "reviewer",
    "browser",
)
GENERATED_ROLE_NAMES = ROLE_NAMES[1:]
ADAPTIVE_ROLES = {"implementer", "complex-implementer"}
ADAPTIVE_EFFORTS = {"bounded": "medium", "complex": "high"}
ROLE_KEYS = {"model", "reasoning_effort"}
PRESETS = {"adaptive", "quality-first", "budget-first"}
BROWSER_DRIVERS = {"agent-browser", "cua", "playwright"}
REASONING_EFFORTS = {
    "none",
    "minimal",
    "low",
    "medium",
    "high",
    "xhigh",
    "max",
    "ultra",
}
GENERATED_HEADER = "# Generated by Doozo. Do not edit this file."
GENERATED_HASH_PREFIX = "# doozo-content-sha256: "
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


class SetupError(Exception):
    """An expected setup error that should be shown without a traceback."""


@dataclass(frozen=True)
class Paths:
    defaults: Path
    user_config: Path
    project_config: Path
    agents_dir: Path


@dataclass(frozen=True)
class Capabilities:
    models: dict[str, frozenset[str]]
    max_workers: Optional[int]
    source: str


@dataclass(frozen=True)
class State:
    paths: Paths
    defaults: dict[str, Any]
    user_config: dict[str, Any]
    user_exists: bool
    project_config: dict[str, Any]
    invocation: dict[str, Any]
    capabilities: Optional[Capabilities]


ROLE_METADATA = {
    "scout": (
        "Read-only explorer that maps affected code and proposes safe work decomposition.",
        "Stay read-only. Trace the relevant execution path, inspect tests and conventions, and report concrete evidence. Propose disjoint scopes for the parent. Do not edit files.",
        "read-only",
    ),
    "implementer": (
        "Focused implementer for a clear, bounded change.",
        "Own only the exact scope assigned by the parent. Keep the change small, preserve local conventions, avoid overlapping writes, and run focused checks.",
        "workspace-write",
    ),
    "complex-implementer": (
        "High-reasoning implementer for difficult, isolated subsystems and integrations.",
        "Own only the difficult scope assigned by the parent. Trace dependencies before editing, make the smallest defensible change, avoid overlapping writes, and validate edge cases with focused tests.",
        "workspace-write",
    ),
    "reviewer": (
        "Read-only reviewer for correctness, regressions, and missing verification.",
        "Review the actual diff and affected paths as a fresh agent. Prioritize correctness, security, data integrity, regressions, and missing tests. Do not edit files.",
        "read-only",
    ),
    "browser": (
        "Browser verifier that exercises the product and captures evidence.",
        "Use the assigned browser route to exercise the requested user flow and inspect the resulting evidence. Do not edit application code. Report the observed behavior and any limitation.",
        "workspace-write",
    ),
}


def is_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def require_object(value: Any, path: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise SetupError(f"{path} must be a JSON object")
    return value


def require_string(value: Any, path: str) -> str:
    if not isinstance(value, str) or not value.strip() or value != value.strip():
        raise SetupError(f"{path} must be a non-empty string")
    return value


def check_unknown_keys(value: dict[str, Any], allowed: set[str], path: str) -> None:
    unknown = sorted(set(value) - allowed)
    if unknown:
        joined = ", ".join(repr(key) for key in unknown)
        raise SetupError(f"{path} has unknown key(s): {joined}")


def validate_role(role_name: str, value: Any, path: str, complete: bool) -> None:
    role = require_object(value, path)
    check_unknown_keys(role, ROLE_KEYS, path)
    if complete:
        missing = sorted(ROLE_KEYS - set(role))
        if missing:
            raise SetupError(f"{path} is missing required key(s): {', '.join(missing)}")

    model = role.get("model")
    effort = role.get("reasoning_effort")
    if "model" in role:
        require_string(model, f"{path}.model")
    if "reasoning_effort" in role:
        effort = require_string(effort, f"{path}.reasoning_effort")
        allowed = REASONING_EFFORTS | {"inherit"} | ({"adaptive"} if role_name in ADAPTIVE_ROLES else set())
        if effort not in allowed:
            raise SetupError(f"{path}.reasoning_effort is not supported by Doozo")

    if complete:
        if role_name == "orchestrator":
            inherited_model = model == "inherit"
            inherited_effort = effort == "inherit"
            if inherited_model != inherited_effort:
                raise SetupError(
                    f"{path} must use inherit for both model and reasoning_effort, or neither"
                )
        elif model == "inherit" or effort == "inherit":
            raise SetupError(f"{path} must choose an explicit model and reasoning_effort")


def validate_config(config: Any, label: str, *, complete: bool) -> dict[str, Any]:
    value = require_object(config, label)
    check_unknown_keys(value, CONFIG_KEYS, label)
    if complete:
        missing = sorted(CONFIG_KEYS - set(value))
        if missing:
            raise SetupError(f"{label} is missing required key(s): {', '.join(missing)}")

    if "schema_version" in value:
        version = value["schema_version"]
        if not is_int(version) or version != 1:
            raise SetupError(f"{label}.schema_version must be integer 1")
    if "preset" in value:
        preset = require_string(value["preset"], f"{label}.preset")
        if preset not in PRESETS:
            raise SetupError(f"{label}.preset must be one of: {', '.join(sorted(PRESETS))}")
    if "max_workers" in value:
        max_workers = value["max_workers"]
        if not is_int(max_workers) or max_workers < 1:
            raise SetupError(f"{label}.max_workers must be an integer of at least 1")
    if "model_fallback" in value and value["model_fallback"] != "disabled":
        raise SetupError(f"{label}.model_fallback must be 'disabled'")
    if "browser" in value:
        browser = require_object(value["browser"], f"{label}.browser")
        check_unknown_keys(browser, {"preferred", "fallback"}, f"{label}.browser")
        if complete:
            missing = sorted({"preferred", "fallback"} - set(browser))
            if missing:
                raise SetupError(
                    f"{label}.browser is missing required key(s): {', '.join(missing)}"
                )
        for field in ("preferred", "fallback"):
            if field not in browser:
                continue
            driver = browser[field]
            if driver is None and field == "fallback":
                continue
            driver = require_string(driver, f"{label}.browser.{field}")
            if driver not in BROWSER_DRIVERS:
                raise SetupError(
                    f"{label}.browser.{field} must be one of: {', '.join(sorted(BROWSER_DRIVERS))}"
                )
        if complete and browser["fallback"] == browser["preferred"]:
            raise SetupError(f"{label}.browser.fallback must differ from preferred when set")
    if "roles" in value:
        roles = require_object(value["roles"], f"{label}.roles")
        check_unknown_keys(roles, set(ROLE_NAMES), f"{label}.roles")
        if complete:
            missing = sorted(set(ROLE_NAMES) - set(roles))
            if missing:
                raise SetupError(f"{label}.roles is missing required role(s): {', '.join(missing)}")
        for role_name, role in roles.items():
            validate_role(role_name, role, f"{label}.roles.{role_name}", complete)
    return value


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    merged = dict(base)
    for key, override_value in override.items():
        base_value = merged.get(key)
        if isinstance(base_value, dict) and isinstance(override_value, dict):
            merged[key] = deep_merge(base_value, override_value)
        else:
            merged[key] = override_value
    return merged


def read_json_file(path: Path, label: str, *, optional: bool) -> tuple[dict[str, Any], bool]:
    if not path.exists():
        if optional:
            return {}, False
        raise SetupError(f"{label} does not exist: {path}")
    if not path.is_file():
        raise SetupError(f"{label} is not a file: {path}")
    try:
        raw = path.read_text(encoding="utf-8")
        value = json.loads(raw)
    except OSError as error:
        raise SetupError(f"could not read {label}: {error}") from error
    except json.JSONDecodeError as error:
        raise SetupError(f"{label} is not valid JSON: {error.msg}") from error
    return require_object(value, label), True


def read_json_argument(argument: Optional[str], label: str) -> dict[str, Any]:
    if argument is None:
        return {}
    candidate_text = argument.strip()
    if candidate_text.startswith("{"):
        try:
            value = json.loads(candidate_text)
        except json.JSONDecodeError as error:
            raise SetupError(f"{label} must be JSON text or a JSON file path: {error.msg}") from error
        return require_object(value, label)
    candidate = Path(argument).expanduser()
    try:
        exists = candidate.exists()
    except OSError as error:
        raise SetupError(f"{label} must be JSON text or a readable JSON file path: {error}") from error
    if exists:
        value, _ = read_json_file(candidate, label, optional=False)
        return value
    try:
        value = json.loads(argument)
    except json.JSONDecodeError as error:
        raise SetupError(f"{label} must be JSON text or a JSON file path: {error.msg}") from error
    return require_object(value, label)


def normalize_efforts(value: Any, path: str) -> frozenset[str]:
    if not isinstance(value, list):
        raise SetupError(f"{path} must be an array")
    efforts: set[str] = set()
    for index, effort in enumerate(value):
        effort = require_string(effort, f"{path}[{index}]")
        if effort not in REASONING_EFFORTS:
            raise SetupError(f"{path}[{index}] is not a supported reasoning effort")
        efforts.add(effort)
    return frozenset(efforts)


def normalize_capabilities(value: Optional[dict[str, Any]]) -> Optional[Capabilities]:
    if value is None:
        return None
    if "data" in value:
        data = value["data"]
        if not isinstance(data, list):
            raise SetupError("capabilities.data must be an array")
        models: dict[str, frozenset[str]] = {}
        for index, entry in enumerate(data):
            entry_path = f"capabilities.data[{index}]"
            entry = require_object(entry, entry_path)
            if entry.get("hidden") is True:
                continue
            model = require_string(entry.get("model"), f"{entry_path}.model")
            raw_efforts = entry.get("supportedReasoningEfforts")
            if not isinstance(raw_efforts, list):
                raise SetupError(f"{entry_path}.supportedReasoningEfforts must be an array")
            efforts: set[str] = set()
            for effort_index, effort in enumerate(raw_efforts):
                effort = require_object(
                    effort,
                    f"{entry_path}.supportedReasoningEfforts[{effort_index}]",
                )
                effort_name = require_string(
                    effort.get("reasoningEffort"),
                    f"{entry_path}.supportedReasoningEfforts[{effort_index}].reasoningEffort",
                )
                if effort_name not in REASONING_EFFORTS:
                    raise SetupError(
                        f"{entry_path}.supportedReasoningEfforts[{effort_index}].reasoningEffort "
                        "is not supported by Doozo"
                    )
                efforts.add(effort_name)
            models[model] = frozenset(efforts)
        return Capabilities(models=models, max_workers=None, source="app-server")

    check_unknown_keys(value, {"models", "max_workers"}, "capabilities")
    if "models" not in value:
        raise SetupError("capabilities must contain either app-server data or models")
    raw_models = require_object(value["models"], "capabilities.models")
    models = {}
    for model, raw_efforts in raw_models.items():
        model = require_string(model, "capabilities.models key")
        if isinstance(raw_efforts, dict):
            check_unknown_keys(raw_efforts, {"reasoning_efforts"}, f"capabilities.models.{model}")
            if "reasoning_efforts" not in raw_efforts:
                raise SetupError(f"capabilities.models.{model} is missing reasoning_efforts")
            raw_efforts = raw_efforts["reasoning_efforts"]
        models[model] = normalize_efforts(raw_efforts, f"capabilities.models.{model}")
    max_workers = value.get("max_workers")
    if max_workers is not None and (not is_int(max_workers) or max_workers < 1):
        raise SetupError("capabilities.max_workers must be an integer of at least 1")
    return Capabilities(models=models, max_workers=max_workers, source="generic")


def route_status(
    config: dict[str, Any], capabilities: Optional[Capabilities], task_complexity: str = "bounded"
) -> dict[str, dict[str, Any]]:
    if capabilities and capabilities.max_workers is not None:
        configured_workers = config["max_workers"]
        if configured_workers > capabilities.max_workers:
            raise SetupError(
                f"max_workers ({configured_workers}) exceeds host limit ({capabilities.max_workers})"
            )

    statuses: dict[str, dict[str, Any]] = {}
    for role_name in ROLE_NAMES:
        role = config["roles"][role_name]
        model = role["model"]
        effort = role["reasoning_effort"]
        policy = "adaptive" if effort == "adaptive" else "fixed"
        if policy == "adaptive":
            effort = ADAPTIVE_EFFORTS[task_complexity]
        if model == "inherit":
            statuses[role_name] = {
                "agent_name": None,
                "model": model,
                "reasoning_effort": effort,
                "reasoning_policy": "inherited",
                "status": "inherited",
                "advertised": False,
                "confirmed": False,
                "capability_source": "not-applicable",
            }
            continue
        if capabilities is None:
            status = "unknown"
            advertised = False
            capability_source = "unknown"
        elif model not in capabilities.models:
            raise SetupError(f"role {role_name} model {model!r} is not advertised by the host")
        elif effort not in capabilities.models[model]:
            raise SetupError(
                f"role {role_name} reasoning_effort {effort!r} is not advertised for model {model!r}"
            )
        else:
            status = "advertised"
            advertised = True
            capability_source = capabilities.source
        statuses[role_name] = {
            "agent_name": None if role_name == "orchestrator" else f"doo-{role_name}",
            "model": model,
            "reasoning_effort": effort,
            "reasoning_policy": policy,
            "status": status,
            "advertised": advertised,
            # Only the host-owned smoke workflow can turn this into confirmed.
            "confirmed": False,
            "capability_source": capability_source,
        }
    return statuses


def toml_string(value: str) -> str:
    # TOML basic strings share JSON's escapes for the characters accepted here.
    return json.dumps(value, ensure_ascii=True)


def rendered_agent_payload(role_name: str, route: dict[str, Any]) -> str:
    description, instructions, sandbox_mode = ROLE_METADATA[role_name]
    agent_name = f"doo-{role_name}"
    return "\n".join(
        (
            f"name = {toml_string(agent_name)}",
            f"description = {toml_string(description)}",
            f"model = {toml_string(route['model'])}",
            f"model_reasoning_effort = {toml_string(route['reasoning_effort'])}",
            f"sandbox_mode = {toml_string(sandbox_mode)}",
            "",
            'developer_instructions = """',
            instructions,
            "Other agents may edit the repository. Preserve their changes and stay in your assigned scope. Do not delegate further unless the parent explicitly assigns that responsibility.",
            '"""',
            "",
        )
    )


def rendered_agent_file(role_name: str, route: dict[str, Any]) -> str:
    payload = rendered_agent_payload(role_name, route)
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return f"{GENERATED_HEADER}\n{GENERATED_HASH_PREFIX}{digest}\n\n{payload}"


def is_unmodified_generated_file(path: Path) -> bool:
    try:
        contents = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    first, separator, remainder = contents.partition("\n")
    if first != GENERATED_HEADER or not separator:
        return False
    hash_line, separator, payload = remainder.partition("\n")
    if not separator or not hash_line.startswith(GENERATED_HASH_PREFIX):
        return False
    digest = hash_line[len(GENERATED_HASH_PREFIX) :]
    if not SHA256_RE.fullmatch(digest):
        return False
    if not payload.startswith("\n"):
        return False
    payload = payload[1:]
    actual = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    return hmac.compare_digest(digest, actual)


def path_exists(path: Path) -> bool:
    return os.path.lexists(path)


def preflight_target(path: Path, label: str) -> None:
    if path_exists(path) and path.is_symlink():
        raise SetupError(f"{label} is a symlink and will not be replaced: {path}")
    if path_exists(path) and path.is_dir():
        raise SetupError(f"{label} is a directory, not a file: {path}")
    parent = path.parent
    if parent.exists() and not parent.is_dir():
        raise SetupError(f"parent for {label} is not a directory: {parent}")


def preflight_agents(agents_dir: Path, agent_files: dict[Path, str]) -> None:
    if agents_dir.exists() and not agents_dir.is_dir():
        raise SetupError(f"agents directory is not a directory: {agents_dir}")
    for path in agent_files:
        preflight_target(path, "generated agent file")
        if path_exists(path) and not is_unmodified_generated_file(path):
            raise SetupError(f"generated agent file was manually modified or collides: {path}")


def backup_path(path: Path) -> Path:
    return path.with_name(f"{path.name}.bak")


def is_valid_config_backup(path: Path) -> bool:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
        validate_config(value, f"backup {path}", complete=False)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, SetupError):
        return False
    return True


def read_existing_bytes(path: Path) -> Optional[bytes]:
    if not path_exists(path):
        return None
    try:
        return path.read_bytes()
    except OSError as error:
        raise SetupError(f"could not read existing file {path}: {error}") from error


def preflight_write_plan(
    config_path: Optional[Path],
    agents_dir: Path,
    agent_files: dict[Path, str],
    planned_files: dict[Path, str],
) -> dict[Path, bytes]:
    planned_paths = list(planned_files)
    seen: set[str] = set()
    for path in planned_paths:
        normalized = os.path.normcase(str(path.resolve()))
        if normalized in seen:
            raise SetupError(f"two Doozo outputs resolve to the same path: {path}")
        seen.add(normalized)
    if config_path is not None:
        preflight_target(config_path, "configuration file")
    preflight_agents(agents_dir, agent_files)
    changed_outputs: dict[Path, bytes] = {}
    for path, contents in planned_files.items():
        previous = read_existing_bytes(path)
        if previous is not None and previous != contents.encode("utf-8"):
            changed_outputs[path] = previous

    backup_paths: set[str] = set()
    planned_normalized = {os.path.normcase(os.path.abspath(path)) for path in planned_paths}
    for path in changed_outputs:
        backup = backup_path(path)
        normalized = os.path.normcase(os.path.abspath(backup))
        if normalized in planned_normalized or normalized in backup_paths:
            raise SetupError(f"backup path collides with a Doozo output: {backup}")
        backup_paths.add(normalized)
        preflight_target(backup, "backup file")
        if not path_exists(backup):
            continue
        valid_backup = (
            is_unmodified_generated_file(backup)
            if path in agent_files
            else is_valid_config_backup(backup)
        )
        if not valid_backup:
            raise SetupError(f"backup file was manually modified or collides: {backup}")
    return changed_outputs


def atomic_write(path: Path, contents: Any) -> bool:
    encoded = contents if isinstance(contents, bytes) else contents.encode("utf-8")
    if path_exists(path):
        try:
            if path.read_bytes() == encoded:
                return False
        except OSError as error:
            raise SetupError(f"could not read existing file {path}: {error}") from error

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
        )
        temporary_path = Path(temporary_name)
        try:
            os.chmod(temporary_path, 0o600)
            with os.fdopen(descriptor, "wb") as temporary_file:
                descriptor = -1
                temporary_file.write(encoded)
                temporary_file.flush()
                os.fsync(temporary_file.fileno())
            os.replace(temporary_path, path)
            if os.name == "posix":
                directory_descriptor = os.open(path.parent, os.O_RDONLY)
                try:
                    os.fsync(directory_descriptor)
                finally:
                    os.close(directory_descriptor)
        finally:
            if descriptor != -1:
                os.close(descriptor)
            if temporary_path.exists():
                temporary_path.unlink()
    except OSError as error:
        raise SetupError(f"could not atomically write {path}: {error}") from error
    return True


def output_paths(paths: Paths) -> dict[str, str]:
    return {
        "defaults": str(paths.defaults),
        "user_config": str(paths.user_config),
        "project_config": str(paths.project_config),
        "agents_dir": str(paths.agents_dir),
    }


def build_result(
    effective: dict[str, Any],
    statuses: dict[str, dict[str, Any]],
    paths: Paths,
    capabilities: Optional[Capabilities],
) -> dict[str, Any]:
    return {
        "effective": effective,
        "route_status": statuses,
        "capabilities_source": capabilities.source if capabilities else "unknown",
        "paths": output_paths(paths),
    }


def effective_config(
    defaults: dict[str, Any],
    user_config: dict[str, Any],
    project_config: dict[str, Any],
    invocation: dict[str, Any],
) -> dict[str, Any]:
    merged = deep_merge(defaults, user_config)
    merged = deep_merge(merged, project_config)
    return deep_merge(merged, invocation)


def load_state(
    args: argparse.Namespace, *, include_project: bool = True, include_invocation: bool = True
) -> State:
    if args.agents_dir is not None:
        agents_dir = Path(args.agents_dir).expanduser()
    elif args.command == "apply" and args.write_scope == "project":
        agents_dir = Path.cwd() / ".codex" / "agents"
    else:
        agents_dir = Path.home() / ".codex" / "agents"
    paths = Paths(
        defaults=Path(args.defaults).expanduser(),
        user_config=Path(args.user_config).expanduser(),
        project_config=Path(args.project_config).expanduser(),
        agents_dir=agents_dir,
    )
    defaults, _ = read_json_file(paths.defaults, "defaults", optional=False)
    user_config, user_exists = read_json_file(paths.user_config, "user config", optional=True)
    if include_project:
        project_config, _ = read_json_file(paths.project_config, "project config", optional=True)
    else:
        project_config = {}
    invocation = (
        read_json_argument(args.invocation_json, "invocation JSON") if include_invocation else {}
    )
    capabilities_input = (
        read_json_argument(args.capabilities_json, "capabilities JSON")
        if args.capabilities_json is not None
        else None
    )

    validate_config(defaults, "defaults", complete=True)
    validate_config(user_config, "user config", complete=False)
    validate_config(project_config, "project config", complete=False)
    validate_config(invocation, "invocation JSON", complete=False)
    capabilities = normalize_capabilities(capabilities_input)
    return State(
        paths=paths,
        defaults=defaults,
        user_config=user_config,
        user_exists=user_exists,
        project_config=project_config,
        invocation=invocation,
        capabilities=capabilities,
    )


def resolve(args: argparse.Namespace) -> dict[str, Any]:
    state = load_state(args)
    effective = effective_config(
        state.defaults, state.user_config, state.project_config, state.invocation
    )
    validate_config(effective, "effective configuration", complete=True)
    statuses = route_status(effective, state.capabilities, args.task_complexity)
    if args.compact:
        return {
            **{key: effective[key] for key in ("preset", "max_workers", "model_fallback", "browser")},
            "route_status": {
                role: {key: route[key] for key in ("agent_name", "model", "reasoning_effort", "reasoning_policy", "status", "confirmed")}
                for role, route in statuses.items()
            },
        }
    return build_result(effective, statuses, state.paths, state.capabilities)


def apply(args: argparse.Namespace) -> dict[str, Any]:
    if args.invocation_json is not None:
        raise SetupError("--invocation-json is only supported by resolve and validate")
    state = load_state(args, include_project=args.write_scope == "project", include_invocation=False)
    paths = state.paths
    defaults = state.defaults
    user_config = state.user_config
    project_config = state.project_config
    settings = read_json_argument(args.settings_json, "settings JSON")
    validate_config(settings, "settings JSON", complete=False)

    config_write: Optional[Tuple[Path, dict[str, Any]]] = None
    if args.write_scope == "user":
        if args.settings_json is not None:
            user_config = deep_merge(user_config, settings)
            if not state.user_exists:
                user_config = deep_merge(defaults, user_config)
            config_write = (paths.user_config, user_config)
        elif not state.user_exists:
            user_config = defaults
            config_write = (paths.user_config, user_config)
    elif args.settings_json is not None:
        project_config = deep_merge(project_config, settings)
        config_write = (paths.project_config, project_config)

    validate_config(user_config, "user config", complete=False)
    validate_config(project_config, "project config", complete=False)
    effective = effective_config(defaults, user_config, project_config, {})
    validate_config(effective, "effective configuration", complete=True)
    statuses = route_status(effective, state.capabilities)

    agent_files = {
        paths.agents_dir / f"doo-{role_name}.toml": rendered_agent_file(
            role_name, statuses[role_name]
        )
        for role_name in GENERATED_ROLE_NAMES
    }
    planned_files: dict[Path, str] = {}
    if config_write is not None:
        path, value = config_write
        planned_files[path] = json.dumps(value, indent=2, sort_keys=True) + "\n"
    planned_files.update(agent_files)
    changed_outputs = preflight_write_plan(
        config_write[0] if config_write is not None else None,
        paths.agents_dir,
        agent_files,
        planned_files,
    )

    written: list[str] = []
    unchanged: list[str] = []
    backups: list[str] = []
    for path, previous in changed_outputs.items():
        backup = backup_path(path)
        atomic_write(backup, previous)
        backups.append(str(backup))
    for path, contents in planned_files.items():
        (written if atomic_write(path, contents) else unchanged).append(str(path))

    result = build_result(effective, statuses, paths, state.capabilities)
    result.update(
        {"valid": True, "written": written, "unchanged": unchanged, "backups": backups}
    )
    return result


def add_common_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--defaults",
        default=str(DEFAULTS_PATH),
        help="defaults.json path (default: bundled defaults.json)",
    )
    parser.add_argument(
        "--user-config",
        default=str(Path.home() / ".config" / "doozo" / "config.json"),
        help="user settings path",
    )
    parser.add_argument(
        "--project-config",
        default=str(Path.cwd() / ".doozo" / "config.json"),
        help="project override path",
    )
    parser.add_argument(
        "--agents-dir",
        help=(
            "directory for generated doo-*.toml custom agents (default: ~/.codex/agents, "
            "or ./.codex/agents for apply --write-scope project)"
        ),
    )
    parser.add_argument(
        "--invocation-json",
        help="ephemeral JSON object or path merged last by resolve/validate; apply rejects it",
    )
    parser.add_argument(
        "--capabilities-json",
        help=(
            "host capabilities JSON object or path; accepts app-server data[] output or "
            "{models: {model: [effort]}, max_workers?: number}"
        ),
    )


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        description="Resolve, validate, or apply Doozo's local configuration."
    )
    commands = result.add_subparsers(dest="command", required=True)
    for command in ("resolve", "validate"):
        child = commands.add_parser(command)
        add_common_arguments(child)
        child.add_argument("--compact", action="store_true", help="emit execution settings without duplicate configuration or paths")
        child.add_argument("--task-complexity", choices=tuple(ADAPTIVE_EFFORTS), default="bounded", help="resolve adaptive worker effort for this task without writing settings")
    apply_parser = commands.add_parser("apply")
    add_common_arguments(apply_parser)
    apply_parser.add_argument(
        "--settings-json",
        help="JSON object or path merged into the selected persisted settings layer",
    )
    apply_parser.add_argument(
        "--write-scope",
        choices=("user", "project"),
        default="user",
        help="persist settings to this layer (default: user)",
    )
    return result


def main(argv: Optional[Iterable[str]] = None) -> int:
    args = parser().parse_args(argv)
    try:
        if args.command == "resolve":
            result = resolve(args)
        elif args.command == "validate":
            result = resolve(args)
            result["valid"] = True
        else:
            result = apply(args)
    except SetupError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
